# Site settings
url: http://www.slizaa.org

#
asciidoctor:
  template_dir: '_templates'
  attributes:
    - source-highlightercoderay

# Build settings
markdown: kramdown
exclude: [slizaa-doc.iml]
gems: [jekyll-asciidoc]
